application: kfs-training
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  GCB_PRODUCT_VERSION: '1.2.0'
  GCB_COURSES_CONFIG: 'course:/Day1:/courses/Day1, course:/Day1:/courses/Day2, course:/Day1:/courses/Day3, course:/Day1:/courses/Day4, course:/Day1:/courses/Day5'
builtins:
- remote_api: on
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /_ah/dev_admin(/.*)?  # provides interactive console
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always
- url: /.*
  script: main.app

